---
title: "Control Tower"
output: 
  flexdashboard::flex_dashboard:
    orientation: columns
    vertical_layout: fill
    theme: cosmo
    navbar:
      - { title: "Source Code", href: "https://github.com/ricardobreis/Exploratory-Data-Analysis-Flights", align: right, icon: "fa-github" }
runtime: shiny
---

```{r setup, include=FALSE}
# Carrega libs
library(flexdashboard)
library(tmap)
library(sf)
library(leaflet)
library(shiny)
library(dplyr)

# Carrega o shapefile
uf <- st_read("~/R-Projetos/Exploratory-Data-Analysis-Flights/data/processed/uf_aereas_shp.shp")
```

Mapa Interativo {data-icon="fa-globe-americas"}
=======================================================================

Column {data-width=300 .sidebar}
-----------------------------------------------------------------------

```{r}
selectInput(
  "companhia",
  label = "Selecione a Companhia Aérea:",
  choices = c("Azul" = "AZU", "Gol" = "GLO", "Latam" = "TAM")
)

selectInput(
  "mes",
  label = "Selecione o Mês:",
  choices = c("Jan" = "Jan", "Fev" = "Fev", "Mar" = "Mar", "Abr" = "Abr", "Mai" = "Mai", "Jun" = "Jun", "Jul" = "Jul")
)

selectInput(
  "coluna",
  label = "Selecione a Variável:",
  choices = c("Decolagens" = "declgns", 
              "Passageiros Pagos" = "pssgrs_p", 
              "Passageiros Grátis" = "pssgrs_g",
              "Carga Paga" = "crg_pg_",
              "Carga Grátis" = "crg_gr_",
              "ASK" = "ask",
              "RPK" = "rpk",
              "Assentos" = "assents")
)

filtered_map <- reactive({
  subset(uf, emprs_s == input$companhia & ms_fctr == input$mes)

})

selected_col <- reactive({
  input$coluna
})

hr()

```

**Nota:**

Esta aplicação foi desenvolvida com o objetivo de estudo apenas. Não posso ser responsabilizado por qualquer decisão tomada com base nas informações contidas neste aplicativo, nem por seu uso por terceiros.

Column {data-width=700}
-----------------------------------------------------------------------

### Mapa Interativo

```{r}

renderLeaflet({

  breaks <- switch( 
     selected_col(), 
     "declgns" = c(1, 50, 100, 500, 1000, 5000, Inf), 
     "pssgrs_p" = c(1, 1000, 50000, 100000, 300000, 500000, 750000, Inf),
     "pssgrs_g" = c(1, 100, 500, 1000, 5000, 10000, 20000, Inf),
     "crg_pg_" = c(1000, 50000, 100000, 300000, 500000, 750000, Inf),
     "crg_gr_" = c(1, 500, 1000, 5000, 10000, 20000, Inf),
     "ask" = c(1000000, 5000000, 10000000, 50000000, 100000000, 500000000, Inf),
     "rpk" = c(1000000, 5000000, 10000000, 50000000, 100000000, 500000000, Inf),
     "assents" = c(100, 50000, 100000, 200000, 300000, 500000, Inf)
  ) 
  
  title <- switch( 
     selected_col(), 
     "declgns" = "Decolagens", 
     "pssgrs_p" = "Passageiros Pagos",
     "pssgrs_g" = "Passageiros Grátis",
     "crg_pg_" = "Carga Paga (Kg)",
     "crg_gr_" = "Carga Grátis (Kg)",
     "ask" = "ASK",
     "rpk" = "RPK",
     "assents" = "Assentos"
  )
  
  leaflet_map <- tm_shape(filtered_map()) +
    
    tm_fill(col = selected_col(), title = title, palette = "Blues", breaks = breaks, id = "nam_stt") +
    tm_borders() +
    tm_style("cobalt")
    
  tmap_leaflet(leaflet_map)

})

```

Mapa Comparativo {data-icon="fa-map-marked-alt"}
=======================================================================

Column {data-width=300 .sidebar}
-----------------------------------------------------------------------
```{r}

checkboxGroupInput(
  "companhia_checkbox", 
  label = "Selecione a(s) Companhia(s) Aérea(s):", 
  choices = list("Azul" = "AZU", "Gol" = "GLO", "Latam" = "TAM"),
  selected = c("AZU", "GLO", "TAM")
  )

hr()

checkboxGroupInput(
  "mes_checkbox", 
  label = "Selecione o(s) Mês(s):", 
  choices = list("Janeiro" = "Jan", "Fevereiro" = "Fev", "Março" = "Mar", "Abril" = "Abr", "Maio" = "Mai", "Junho" = "Jun", "Julho" = "Jul"),
  selected = c("Jan", "Fev", "Mar")
  )

hr()

selectInput(
  "coluna_select",
  label = "Selecione a Variável:",
  choices = c("Decolagens" = "declgns", 
              "Passageiros Pagos" = "pssgrs_p", 
              "Passageiros Grátis" = "pssgrs_g",
              "Carga Paga" = "crg_pg_",
              "Carga Grátis" = "crg_gr_",
              "ASK" = "ask",
              "RPK" = "rpk",
              "Assentos" = "assents")
)

```

Column {data-width=700}
-----------------------------------------------------------------------

```{r}

filtered_map_comparative <- reactive({
  subset(uf, emprs_s %in% input$companhia_checkbox & ms_fctr %in% input$mes_checkbox) %>%
    mutate(ms_fctr  =  factor(ms_fctr, levels = input$mes_checkbox)) %>%
    arrange(ms_fctr)  
})

selected_col_comparative <- reactive({
  input$coluna_select
})

```

### Mapa Comparativo

```{r}
renderPlot({
  
  breaks <- switch( 
     selected_col_comparative(), 
     "declgns" = c(1, 50, 100, 500, 1000, 5000, Inf), 
     "pssgrs_p" = c(1, 1000, 50000, 100000, 300000, 500000, 750000, Inf),
     "pssgrs_g" = c(1, 100, 500, 1000, 5000, 10000, 20000, Inf),
     "crg_pg_" = c(1000, 50000, 100000, 300000, 500000, 750000, Inf),
     "crg_gr_" = c(1, 500, 1000, 5000, 10000, 20000, Inf),
     "ask" = c(1000000, 5000000, 10000000, 50000000, 100000000, 500000000, Inf),
     "rpk" = c(1000000, 5000000, 10000000, 50000000, 100000000, 500000000, Inf),
     "assents" = c(100, 50000, 100000, 200000, 300000, 500000, Inf)
  ) 
  
  title <- switch( 
     selected_col_comparative(), 
     "declgns" = "Decolagens", 
     "pssgrs_p" = "Passageiros Pagos",
     "pssgrs_g" = "Passageiros Grátis",
     "crg_pg_" = "Carga Paga (Kg)",
     "crg_gr_" = "Carga Grátis (Kg)",
     "ask" = "ASK",
     "rpk" = "RPK",
     "assents" = "Assentos"
  )
  
  facets_map <- tm_shape(filtered_map_comparative()) +
    tm_fill(palette = "Blues", col = selected_col_comparative(), title = title, breaks = breaks) +
    tm_borders(alpha = 0.2) +
    tm_facets(by = c("emprs_s", "ms_fctr"), free.coords = FALSE) +
    tm_layout(legend.title.size = 1.4, legend.text.size = 1.1, frame = "#efefef", panel.label.size = 1.5, panel.label.bg.color = "#efefef")
  
  facets_map
  
})
```
